//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZHXY.Application.PushService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://passport.nchu.edu.cn/", ConfigurationName="PushService.数据中心接口服务Soap")]
    public interface 数据中心接口服务Soap {
        
        // CODEGEN: 命名空间 http://passport.nchu.edu.cn/ 的元素名称 SiteID 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://passport.nchu.edu.cn/GetAllOULists", ReplyAction="*")]
        ZHXY.Application.PushService.GetAllOUListsResponse GetAllOULists(ZHXY.Application.PushService.GetAllOUListsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://passport.nchu.edu.cn/GetAllOULists", ReplyAction="*")]
        System.Threading.Tasks.Task<ZHXY.Application.PushService.GetAllOUListsResponse> GetAllOUListsAsync(ZHXY.Application.PushService.GetAllOUListsRequest request);
        
        // CODEGEN: 命名空间 http://passport.nchu.edu.cn/ 的元素名称 SiteID 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://passport.nchu.edu.cn/GetOUList", ReplyAction="*")]
        ZHXY.Application.PushService.GetOUListResponse GetOUList(ZHXY.Application.PushService.GetOUListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://passport.nchu.edu.cn/GetOUList", ReplyAction="*")]
        System.Threading.Tasks.Task<ZHXY.Application.PushService.GetOUListResponse> GetOUListAsync(ZHXY.Application.PushService.GetOUListRequest request);
        
        // CODEGEN: 命名空间 http://passport.nchu.edu.cn/ 的元素名称 SiteID 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://passport.nchu.edu.cn/UpdateStudentClassNo", ReplyAction="*")]
        ZHXY.Application.PushService.UpdateStudentClassNoResponse UpdateStudentClassNo(ZHXY.Application.PushService.UpdateStudentClassNoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://passport.nchu.edu.cn/UpdateStudentClassNo", ReplyAction="*")]
        System.Threading.Tasks.Task<ZHXY.Application.PushService.UpdateStudentClassNoResponse> UpdateStudentClassNoAsync(ZHXY.Application.PushService.UpdateStudentClassNoRequest request);
        
        // CODEGEN: 命名空间 http://passport.nchu.edu.cn/ 的元素名称 SiteID 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://passport.nchu.edu.cn/UpdateStudentStatus", ReplyAction="*")]
        ZHXY.Application.PushService.UpdateStudentStatusResponse UpdateStudentStatus(ZHXY.Application.PushService.UpdateStudentStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://passport.nchu.edu.cn/UpdateStudentStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<ZHXY.Application.PushService.UpdateStudentStatusResponse> UpdateStudentStatusAsync(ZHXY.Application.PushService.UpdateStudentStatusRequest request);
        
        // CODEGEN: 命名空间 http://passport.nchu.edu.cn/ 的元素名称 ClassID 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://passport.nchu.edu.cn/News_GetNewsList", ReplyAction="*")]
        ZHXY.Application.PushService.News_GetNewsListResponse News_GetNewsList(ZHXY.Application.PushService.News_GetNewsListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://passport.nchu.edu.cn/News_GetNewsList", ReplyAction="*")]
        System.Threading.Tasks.Task<ZHXY.Application.PushService.News_GetNewsListResponse> News_GetNewsListAsync(ZHXY.Application.PushService.News_GetNewsListRequest request);
        
        // CODEGEN: 命名空间 http://passport.nchu.edu.cn/ 的元素名称 News_GetTopNewsListResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://passport.nchu.edu.cn/News_GetTopNewsList", ReplyAction="*")]
        ZHXY.Application.PushService.News_GetTopNewsListResponse News_GetTopNewsList(ZHXY.Application.PushService.News_GetTopNewsListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://passport.nchu.edu.cn/News_GetTopNewsList", ReplyAction="*")]
        System.Threading.Tasks.Task<ZHXY.Application.PushService.News_GetTopNewsListResponse> News_GetTopNewsListAsync(ZHXY.Application.PushService.News_GetTopNewsListRequest request);
        
        // CODEGEN: 命名空间 http://passport.nchu.edu.cn/ 的元素名称 SiteID 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://passport.nchu.edu.cn/Portal_GetNoticeList", ReplyAction="*")]
        ZHXY.Application.PushService.Portal_GetNoticeListResponse Portal_GetNoticeList(ZHXY.Application.PushService.Portal_GetNoticeListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://passport.nchu.edu.cn/Portal_GetNoticeList", ReplyAction="*")]
        System.Threading.Tasks.Task<ZHXY.Application.PushService.Portal_GetNoticeListResponse> Portal_GetNoticeListAsync(ZHXY.Application.PushService.Portal_GetNoticeListRequest request);
        
        // CODEGEN: 命名空间 http://passport.nchu.edu.cn/ 的元素名称 SiteID 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://passport.nchu.edu.cn/Portal_GetNoticeContent", ReplyAction="*")]
        ZHXY.Application.PushService.Portal_GetNoticeContentResponse Portal_GetNoticeContent(ZHXY.Application.PushService.Portal_GetNoticeContentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://passport.nchu.edu.cn/Portal_GetNoticeContent", ReplyAction="*")]
        System.Threading.Tasks.Task<ZHXY.Application.PushService.Portal_GetNoticeContentResponse> Portal_GetNoticeContentAsync(ZHXY.Application.PushService.Portal_GetNoticeContentRequest request);
        
        // CODEGEN: 命名空间 http://passport.nchu.edu.cn/ 的元素名称 SiteID 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://passport.nchu.edu.cn/Portal_SetNoticeReadStatus", ReplyAction="*")]
        ZHXY.Application.PushService.Portal_SetNoticeReadStatusResponse Portal_SetNoticeReadStatus(ZHXY.Application.PushService.Portal_SetNoticeReadStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://passport.nchu.edu.cn/Portal_SetNoticeReadStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<ZHXY.Application.PushService.Portal_SetNoticeReadStatusResponse> Portal_SetNoticeReadStatusAsync(ZHXY.Application.PushService.Portal_SetNoticeReadStatusRequest request);
        
        // CODEGEN: 命名空间 http://passport.nchu.edu.cn/ 的元素名称 SiteID 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://passport.nchu.edu.cn/Portal_GetAffairList", ReplyAction="*")]
        ZHXY.Application.PushService.Portal_GetAffairListResponse Portal_GetAffairList(ZHXY.Application.PushService.Portal_GetAffairListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://passport.nchu.edu.cn/Portal_GetAffairList", ReplyAction="*")]
        System.Threading.Tasks.Task<ZHXY.Application.PushService.Portal_GetAffairListResponse> Portal_GetAffairListAsync(ZHXY.Application.PushService.Portal_GetAffairListRequest request);
        
        // CODEGEN: 命名空间 http://passport.nchu.edu.cn/ 的元素名称 SiteID 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://passport.nchu.edu.cn/Portal_SendInstantMessage", ReplyAction="*")]
        ZHXY.Application.PushService.Portal_SendInstantMessageResponse Portal_SendInstantMessage(ZHXY.Application.PushService.Portal_SendInstantMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://passport.nchu.edu.cn/Portal_SendInstantMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<ZHXY.Application.PushService.Portal_SendInstantMessageResponse> Portal_SendInstantMessageAsync(ZHXY.Application.PushService.Portal_SendInstantMessageRequest request);
        
        // CODEGEN: 命名空间 http://passport.nchu.edu.cn/ 的元素名称 SiteID 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://passport.nchu.edu.cn/GetMiddleLeaderList", ReplyAction="*")]
        ZHXY.Application.PushService.GetMiddleLeaderListResponse GetMiddleLeaderList(ZHXY.Application.PushService.GetMiddleLeaderListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://passport.nchu.edu.cn/GetMiddleLeaderList", ReplyAction="*")]
        System.Threading.Tasks.Task<ZHXY.Application.PushService.GetMiddleLeaderListResponse> GetMiddleLeaderListAsync(ZHXY.Application.PushService.GetMiddleLeaderListRequest request);
        
        // CODEGEN: 命名空间 http://passport.nchu.edu.cn/ 的元素名称 SiteID 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://passport.nchu.edu.cn/Portal_GetNotices", ReplyAction="*")]
        ZHXY.Application.PushService.Portal_GetNoticesResponse Portal_GetNotices(ZHXY.Application.PushService.Portal_GetNoticesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://passport.nchu.edu.cn/Portal_GetNotices", ReplyAction="*")]
        System.Threading.Tasks.Task<ZHXY.Application.PushService.Portal_GetNoticesResponse> Portal_GetNoticesAsync(ZHXY.Application.PushService.Portal_GetNoticesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllOUListsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllOULists", Namespace="http://passport.nchu.edu.cn/", Order=0)]
        public ZHXY.Application.PushService.GetAllOUListsRequestBody Body;
        
        public GetAllOUListsRequest() {
        }
        
        public GetAllOUListsRequest(ZHXY.Application.PushService.GetAllOUListsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://passport.nchu.edu.cn/")]
    public partial class GetAllOUListsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SiteID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public bool IsTeacher;
        
        public GetAllOUListsRequestBody() {
        }
        
        public GetAllOUListsRequestBody(string SiteID, bool IsTeacher) {
            this.SiteID = SiteID;
            this.IsTeacher = IsTeacher;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllOUListsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllOUListsResponse", Namespace="http://passport.nchu.edu.cn/", Order=0)]
        public ZHXY.Application.PushService.GetAllOUListsResponseBody Body;
        
        public GetAllOUListsResponse() {
        }
        
        public GetAllOUListsResponse(ZHXY.Application.PushService.GetAllOUListsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://passport.nchu.edu.cn/")]
    public partial class GetAllOUListsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllOUListsResult;
        
        public GetAllOUListsResponseBody() {
        }
        
        public GetAllOUListsResponseBody(string GetAllOUListsResult) {
            this.GetAllOUListsResult = GetAllOUListsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOUListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOUList", Namespace="http://passport.nchu.edu.cn/", Order=0)]
        public ZHXY.Application.PushService.GetOUListRequestBody Body;
        
        public GetOUListRequest() {
        }
        
        public GetOUListRequest(ZHXY.Application.PushService.GetOUListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://passport.nchu.edu.cn/")]
    public partial class GetOUListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SiteID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ouname;
        
        public GetOUListRequestBody() {
        }
        
        public GetOUListRequestBody(string SiteID, string ouname) {
            this.SiteID = SiteID;
            this.ouname = ouname;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOUListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOUListResponse", Namespace="http://passport.nchu.edu.cn/", Order=0)]
        public ZHXY.Application.PushService.GetOUListResponseBody Body;
        
        public GetOUListResponse() {
        }
        
        public GetOUListResponse(ZHXY.Application.PushService.GetOUListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://passport.nchu.edu.cn/")]
    public partial class GetOUListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetOUListResult;
        
        public GetOUListResponseBody() {
        }
        
        public GetOUListResponseBody(string GetOUListResult) {
            this.GetOUListResult = GetOUListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateStudentClassNoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateStudentClassNo", Namespace="http://passport.nchu.edu.cn/", Order=0)]
        public ZHXY.Application.PushService.UpdateStudentClassNoRequestBody Body;
        
        public UpdateStudentClassNoRequest() {
        }
        
        public UpdateStudentClassNoRequest(ZHXY.Application.PushService.UpdateStudentClassNoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://passport.nchu.edu.cn/")]
    public partial class UpdateStudentClassNoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SiteID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string StuNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string NewClassNo;
        
        public UpdateStudentClassNoRequestBody() {
        }
        
        public UpdateStudentClassNoRequestBody(string SiteID, string StuNo, string NewClassNo) {
            this.SiteID = SiteID;
            this.StuNo = StuNo;
            this.NewClassNo = NewClassNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateStudentClassNoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateStudentClassNoResponse", Namespace="http://passport.nchu.edu.cn/", Order=0)]
        public ZHXY.Application.PushService.UpdateStudentClassNoResponseBody Body;
        
        public UpdateStudentClassNoResponse() {
        }
        
        public UpdateStudentClassNoResponse(ZHXY.Application.PushService.UpdateStudentClassNoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://passport.nchu.edu.cn/")]
    public partial class UpdateStudentClassNoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateStudentClassNoResult;
        
        public UpdateStudentClassNoResponseBody() {
        }
        
        public UpdateStudentClassNoResponseBody(string UpdateStudentClassNoResult) {
            this.UpdateStudentClassNoResult = UpdateStudentClassNoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateStudentStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateStudentStatus", Namespace="http://passport.nchu.edu.cn/", Order=0)]
        public ZHXY.Application.PushService.UpdateStudentStatusRequestBody Body;
        
        public UpdateStudentStatusRequest() {
        }
        
        public UpdateStudentStatusRequest(ZHXY.Application.PushService.UpdateStudentStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://passport.nchu.edu.cn/")]
    public partial class UpdateStudentStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SiteID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string StuNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Status;
        
        public UpdateStudentStatusRequestBody() {
        }
        
        public UpdateStudentStatusRequestBody(string SiteID, string StuNo, string Status) {
            this.SiteID = SiteID;
            this.StuNo = StuNo;
            this.Status = Status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateStudentStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateStudentStatusResponse", Namespace="http://passport.nchu.edu.cn/", Order=0)]
        public ZHXY.Application.PushService.UpdateStudentStatusResponseBody Body;
        
        public UpdateStudentStatusResponse() {
        }
        
        public UpdateStudentStatusResponse(ZHXY.Application.PushService.UpdateStudentStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://passport.nchu.edu.cn/")]
    public partial class UpdateStudentStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateStudentStatusResult;
        
        public UpdateStudentStatusResponseBody() {
        }
        
        public UpdateStudentStatusResponseBody(string UpdateStudentStatusResult) {
            this.UpdateStudentStatusResult = UpdateStudentStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class News_GetNewsListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="News_GetNewsList", Namespace="http://passport.nchu.edu.cn/", Order=0)]
        public ZHXY.Application.PushService.News_GetNewsListRequestBody Body;
        
        public News_GetNewsListRequest() {
        }
        
        public News_GetNewsListRequest(ZHXY.Application.PushService.News_GetNewsListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://passport.nchu.edu.cn/")]
    public partial class News_GetNewsListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ClassID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string PageSize;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PageIndex;
        
        public News_GetNewsListRequestBody() {
        }
        
        public News_GetNewsListRequestBody(string ClassID, string PageSize, string PageIndex) {
            this.ClassID = ClassID;
            this.PageSize = PageSize;
            this.PageIndex = PageIndex;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class News_GetNewsListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="News_GetNewsListResponse", Namespace="http://passport.nchu.edu.cn/", Order=0)]
        public ZHXY.Application.PushService.News_GetNewsListResponseBody Body;
        
        public News_GetNewsListResponse() {
        }
        
        public News_GetNewsListResponse(ZHXY.Application.PushService.News_GetNewsListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://passport.nchu.edu.cn/")]
    public partial class News_GetNewsListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string News_GetNewsListResult;
        
        public News_GetNewsListResponseBody() {
        }
        
        public News_GetNewsListResponseBody(string News_GetNewsListResult) {
            this.News_GetNewsListResult = News_GetNewsListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class News_GetTopNewsListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="News_GetTopNewsList", Namespace="http://passport.nchu.edu.cn/", Order=0)]
        public ZHXY.Application.PushService.News_GetTopNewsListRequestBody Body;
        
        public News_GetTopNewsListRequest() {
        }
        
        public News_GetTopNewsListRequest(ZHXY.Application.PushService.News_GetTopNewsListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://passport.nchu.edu.cn/")]
    public partial class News_GetTopNewsListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int TopNum;
        
        public News_GetTopNewsListRequestBody() {
        }
        
        public News_GetTopNewsListRequestBody(int TopNum) {
            this.TopNum = TopNum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class News_GetTopNewsListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="News_GetTopNewsListResponse", Namespace="http://passport.nchu.edu.cn/", Order=0)]
        public ZHXY.Application.PushService.News_GetTopNewsListResponseBody Body;
        
        public News_GetTopNewsListResponse() {
        }
        
        public News_GetTopNewsListResponse(ZHXY.Application.PushService.News_GetTopNewsListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://passport.nchu.edu.cn/")]
    public partial class News_GetTopNewsListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string News_GetTopNewsListResult;
        
        public News_GetTopNewsListResponseBody() {
        }
        
        public News_GetTopNewsListResponseBody(string News_GetTopNewsListResult) {
            this.News_GetTopNewsListResult = News_GetTopNewsListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Portal_GetNoticeListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Portal_GetNoticeList", Namespace="http://passport.nchu.edu.cn/", Order=0)]
        public ZHXY.Application.PushService.Portal_GetNoticeListRequestBody Body;
        
        public Portal_GetNoticeListRequest() {
        }
        
        public Portal_GetNoticeListRequest(ZHXY.Application.PushService.Portal_GetNoticeListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://passport.nchu.edu.cn/")]
    public partial class Portal_GetNoticeListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SiteID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string TypeID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SearchType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string SearchText;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int PageIndex;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int PageSize;
        
        public Portal_GetNoticeListRequestBody() {
        }
        
        public Portal_GetNoticeListRequestBody(string SiteID, string TypeID, string SearchType, string SearchText, int PageIndex, int PageSize) {
            this.SiteID = SiteID;
            this.TypeID = TypeID;
            this.SearchType = SearchType;
            this.SearchText = SearchText;
            this.PageIndex = PageIndex;
            this.PageSize = PageSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Portal_GetNoticeListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Portal_GetNoticeListResponse", Namespace="http://passport.nchu.edu.cn/", Order=0)]
        public ZHXY.Application.PushService.Portal_GetNoticeListResponseBody Body;
        
        public Portal_GetNoticeListResponse() {
        }
        
        public Portal_GetNoticeListResponse(ZHXY.Application.PushService.Portal_GetNoticeListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://passport.nchu.edu.cn/")]
    public partial class Portal_GetNoticeListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Portal_GetNoticeListResult;
        
        public Portal_GetNoticeListResponseBody() {
        }
        
        public Portal_GetNoticeListResponseBody(string Portal_GetNoticeListResult) {
            this.Portal_GetNoticeListResult = Portal_GetNoticeListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Portal_GetNoticeContentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Portal_GetNoticeContent", Namespace="http://passport.nchu.edu.cn/", Order=0)]
        public ZHXY.Application.PushService.Portal_GetNoticeContentRequestBody Body;
        
        public Portal_GetNoticeContentRequest() {
        }
        
        public Portal_GetNoticeContentRequest(ZHXY.Application.PushService.Portal_GetNoticeContentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://passport.nchu.edu.cn/")]
    public partial class Portal_GetNoticeContentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SiteID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Guid;
        
        public Portal_GetNoticeContentRequestBody() {
        }
        
        public Portal_GetNoticeContentRequestBody(string SiteID, string Guid) {
            this.SiteID = SiteID;
            this.Guid = Guid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Portal_GetNoticeContentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Portal_GetNoticeContentResponse", Namespace="http://passport.nchu.edu.cn/", Order=0)]
        public ZHXY.Application.PushService.Portal_GetNoticeContentResponseBody Body;
        
        public Portal_GetNoticeContentResponse() {
        }
        
        public Portal_GetNoticeContentResponse(ZHXY.Application.PushService.Portal_GetNoticeContentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://passport.nchu.edu.cn/")]
    public partial class Portal_GetNoticeContentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public object Portal_GetNoticeContentResult;
        
        public Portal_GetNoticeContentResponseBody() {
        }
        
        public Portal_GetNoticeContentResponseBody(object Portal_GetNoticeContentResult) {
            this.Portal_GetNoticeContentResult = Portal_GetNoticeContentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Portal_SetNoticeReadStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Portal_SetNoticeReadStatus", Namespace="http://passport.nchu.edu.cn/", Order=0)]
        public ZHXY.Application.PushService.Portal_SetNoticeReadStatusRequestBody Body;
        
        public Portal_SetNoticeReadStatusRequest() {
        }
        
        public Portal_SetNoticeReadStatusRequest(ZHXY.Application.PushService.Portal_SetNoticeReadStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://passport.nchu.edu.cn/")]
    public partial class Portal_SetNoticeReadStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SiteID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Guid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Name;
        
        public Portal_SetNoticeReadStatusRequestBody() {
        }
        
        public Portal_SetNoticeReadStatusRequestBody(string SiteID, string Guid, string Name) {
            this.SiteID = SiteID;
            this.Guid = Guid;
            this.Name = Name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Portal_SetNoticeReadStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Portal_SetNoticeReadStatusResponse", Namespace="http://passport.nchu.edu.cn/", Order=0)]
        public ZHXY.Application.PushService.Portal_SetNoticeReadStatusResponseBody Body;
        
        public Portal_SetNoticeReadStatusResponse() {
        }
        
        public Portal_SetNoticeReadStatusResponse(ZHXY.Application.PushService.Portal_SetNoticeReadStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://passport.nchu.edu.cn/")]
    public partial class Portal_SetNoticeReadStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Portal_SetNoticeReadStatusResult;
        
        public Portal_SetNoticeReadStatusResponseBody() {
        }
        
        public Portal_SetNoticeReadStatusResponseBody(string Portal_SetNoticeReadStatusResult) {
            this.Portal_SetNoticeReadStatusResult = Portal_SetNoticeReadStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Portal_GetAffairListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Portal_GetAffairList", Namespace="http://passport.nchu.edu.cn/", Order=0)]
        public ZHXY.Application.PushService.Portal_GetAffairListRequestBody Body;
        
        public Portal_GetAffairListRequest() {
        }
        
        public Portal_GetAffairListRequest(ZHXY.Application.PushService.Portal_GetAffairListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://passport.nchu.edu.cn/")]
    public partial class Portal_GetAffairListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SiteID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string UID;
        
        public Portal_GetAffairListRequestBody() {
        }
        
        public Portal_GetAffairListRequestBody(string SiteID, string UID) {
            this.SiteID = SiteID;
            this.UID = UID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Portal_GetAffairListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Portal_GetAffairListResponse", Namespace="http://passport.nchu.edu.cn/", Order=0)]
        public ZHXY.Application.PushService.Portal_GetAffairListResponseBody Body;
        
        public Portal_GetAffairListResponse() {
        }
        
        public Portal_GetAffairListResponse(ZHXY.Application.PushService.Portal_GetAffairListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://passport.nchu.edu.cn/")]
    public partial class Portal_GetAffairListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Portal_GetAffairListResult;
        
        public Portal_GetAffairListResponseBody() {
        }
        
        public Portal_GetAffairListResponseBody(string Portal_GetAffairListResult) {
            this.Portal_GetAffairListResult = Portal_GetAffairListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Portal_SendInstantMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Portal_SendInstantMessage", Namespace="http://passport.nchu.edu.cn/", Order=0)]
        public ZHXY.Application.PushService.Portal_SendInstantMessageRequestBody Body;
        
        public Portal_SendInstantMessageRequest() {
        }
        
        public Portal_SendInstantMessageRequest(ZHXY.Application.PushService.Portal_SendInstantMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://passport.nchu.edu.cn/")]
    public partial class Portal_SendInstantMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SiteID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string UID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string MsgType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string MsgContent;
        
        public Portal_SendInstantMessageRequestBody() {
        }
        
        public Portal_SendInstantMessageRequestBody(string SiteID, string UID, string MsgType, string MsgContent) {
            this.SiteID = SiteID;
            this.UID = UID;
            this.MsgType = MsgType;
            this.MsgContent = MsgContent;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Portal_SendInstantMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Portal_SendInstantMessageResponse", Namespace="http://passport.nchu.edu.cn/", Order=0)]
        public ZHXY.Application.PushService.Portal_SendInstantMessageResponseBody Body;
        
        public Portal_SendInstantMessageResponse() {
        }
        
        public Portal_SendInstantMessageResponse(ZHXY.Application.PushService.Portal_SendInstantMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://passport.nchu.edu.cn/")]
    public partial class Portal_SendInstantMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Portal_SendInstantMessageResult;
        
        public Portal_SendInstantMessageResponseBody() {
        }
        
        public Portal_SendInstantMessageResponseBody(string Portal_SendInstantMessageResult) {
            this.Portal_SendInstantMessageResult = Portal_SendInstantMessageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMiddleLeaderListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMiddleLeaderList", Namespace="http://passport.nchu.edu.cn/", Order=0)]
        public ZHXY.Application.PushService.GetMiddleLeaderListRequestBody Body;
        
        public GetMiddleLeaderListRequest() {
        }
        
        public GetMiddleLeaderListRequest(ZHXY.Application.PushService.GetMiddleLeaderListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://passport.nchu.edu.cn/")]
    public partial class GetMiddleLeaderListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SiteID;
        
        public GetMiddleLeaderListRequestBody() {
        }
        
        public GetMiddleLeaderListRequestBody(string SiteID) {
            this.SiteID = SiteID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMiddleLeaderListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMiddleLeaderListResponse", Namespace="http://passport.nchu.edu.cn/", Order=0)]
        public ZHXY.Application.PushService.GetMiddleLeaderListResponseBody Body;
        
        public GetMiddleLeaderListResponse() {
        }
        
        public GetMiddleLeaderListResponse(ZHXY.Application.PushService.GetMiddleLeaderListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://passport.nchu.edu.cn/")]
    public partial class GetMiddleLeaderListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetMiddleLeaderListResult;
        
        public GetMiddleLeaderListResponseBody() {
        }
        
        public GetMiddleLeaderListResponseBody(string GetMiddleLeaderListResult) {
            this.GetMiddleLeaderListResult = GetMiddleLeaderListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Portal_GetNoticesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Portal_GetNotices", Namespace="http://passport.nchu.edu.cn/", Order=0)]
        public ZHXY.Application.PushService.Portal_GetNoticesRequestBody Body;
        
        public Portal_GetNoticesRequest() {
        }
        
        public Portal_GetNoticesRequest(ZHXY.Application.PushService.Portal_GetNoticesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://passport.nchu.edu.cn/")]
    public partial class Portal_GetNoticesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SiteID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string UID;
        
        public Portal_GetNoticesRequestBody() {
        }
        
        public Portal_GetNoticesRequestBody(string SiteID, string UID) {
            this.SiteID = SiteID;
            this.UID = UID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Portal_GetNoticesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Portal_GetNoticesResponse", Namespace="http://passport.nchu.edu.cn/", Order=0)]
        public ZHXY.Application.PushService.Portal_GetNoticesResponseBody Body;
        
        public Portal_GetNoticesResponse() {
        }
        
        public Portal_GetNoticesResponse(ZHXY.Application.PushService.Portal_GetNoticesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://passport.nchu.edu.cn/")]
    public partial class Portal_GetNoticesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Portal_GetNoticesResult;
        
        public Portal_GetNoticesResponseBody() {
        }
        
        public Portal_GetNoticesResponseBody(string Portal_GetNoticesResult) {
            this.Portal_GetNoticesResult = Portal_GetNoticesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface 数据中心接口服务SoapChannel : ZHXY.Application.PushService.数据中心接口服务Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class 数据中心接口服务SoapClient : System.ServiceModel.ClientBase<ZHXY.Application.PushService.数据中心接口服务Soap>, ZHXY.Application.PushService.数据中心接口服务Soap {
        
        public 数据中心接口服务SoapClient() {
        }
        
        public 数据中心接口服务SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public 数据中心接口服务SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public 数据中心接口服务SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public 数据中心接口服务SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ZHXY.Application.PushService.GetAllOUListsResponse ZHXY.Application.PushService.数据中心接口服务Soap.GetAllOULists(ZHXY.Application.PushService.GetAllOUListsRequest request) {
            return base.Channel.GetAllOULists(request);
        }
        
        public string GetAllOULists(string SiteID, bool IsTeacher) {
            ZHXY.Application.PushService.GetAllOUListsRequest inValue = new ZHXY.Application.PushService.GetAllOUListsRequest();
            inValue.Body = new ZHXY.Application.PushService.GetAllOUListsRequestBody();
            inValue.Body.SiteID = SiteID;
            inValue.Body.IsTeacher = IsTeacher;
            ZHXY.Application.PushService.GetAllOUListsResponse retVal = ((ZHXY.Application.PushService.数据中心接口服务Soap)(this)).GetAllOULists(inValue);
            return retVal.Body.GetAllOUListsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ZHXY.Application.PushService.GetAllOUListsResponse> ZHXY.Application.PushService.数据中心接口服务Soap.GetAllOUListsAsync(ZHXY.Application.PushService.GetAllOUListsRequest request) {
            return base.Channel.GetAllOUListsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ZHXY.Application.PushService.GetAllOUListsResponse> GetAllOUListsAsync(string SiteID, bool IsTeacher) {
            ZHXY.Application.PushService.GetAllOUListsRequest inValue = new ZHXY.Application.PushService.GetAllOUListsRequest();
            inValue.Body = new ZHXY.Application.PushService.GetAllOUListsRequestBody();
            inValue.Body.SiteID = SiteID;
            inValue.Body.IsTeacher = IsTeacher;
            return ((ZHXY.Application.PushService.数据中心接口服务Soap)(this)).GetAllOUListsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ZHXY.Application.PushService.GetOUListResponse ZHXY.Application.PushService.数据中心接口服务Soap.GetOUList(ZHXY.Application.PushService.GetOUListRequest request) {
            return base.Channel.GetOUList(request);
        }
        
        public string GetOUList(string SiteID, string ouname) {
            ZHXY.Application.PushService.GetOUListRequest inValue = new ZHXY.Application.PushService.GetOUListRequest();
            inValue.Body = new ZHXY.Application.PushService.GetOUListRequestBody();
            inValue.Body.SiteID = SiteID;
            inValue.Body.ouname = ouname;
            ZHXY.Application.PushService.GetOUListResponse retVal = ((ZHXY.Application.PushService.数据中心接口服务Soap)(this)).GetOUList(inValue);
            return retVal.Body.GetOUListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ZHXY.Application.PushService.GetOUListResponse> ZHXY.Application.PushService.数据中心接口服务Soap.GetOUListAsync(ZHXY.Application.PushService.GetOUListRequest request) {
            return base.Channel.GetOUListAsync(request);
        }
        
        public System.Threading.Tasks.Task<ZHXY.Application.PushService.GetOUListResponse> GetOUListAsync(string SiteID, string ouname) {
            ZHXY.Application.PushService.GetOUListRequest inValue = new ZHXY.Application.PushService.GetOUListRequest();
            inValue.Body = new ZHXY.Application.PushService.GetOUListRequestBody();
            inValue.Body.SiteID = SiteID;
            inValue.Body.ouname = ouname;
            return ((ZHXY.Application.PushService.数据中心接口服务Soap)(this)).GetOUListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ZHXY.Application.PushService.UpdateStudentClassNoResponse ZHXY.Application.PushService.数据中心接口服务Soap.UpdateStudentClassNo(ZHXY.Application.PushService.UpdateStudentClassNoRequest request) {
            return base.Channel.UpdateStudentClassNo(request);
        }
        
        public string UpdateStudentClassNo(string SiteID, string StuNo, string NewClassNo) {
            ZHXY.Application.PushService.UpdateStudentClassNoRequest inValue = new ZHXY.Application.PushService.UpdateStudentClassNoRequest();
            inValue.Body = new ZHXY.Application.PushService.UpdateStudentClassNoRequestBody();
            inValue.Body.SiteID = SiteID;
            inValue.Body.StuNo = StuNo;
            inValue.Body.NewClassNo = NewClassNo;
            ZHXY.Application.PushService.UpdateStudentClassNoResponse retVal = ((ZHXY.Application.PushService.数据中心接口服务Soap)(this)).UpdateStudentClassNo(inValue);
            return retVal.Body.UpdateStudentClassNoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ZHXY.Application.PushService.UpdateStudentClassNoResponse> ZHXY.Application.PushService.数据中心接口服务Soap.UpdateStudentClassNoAsync(ZHXY.Application.PushService.UpdateStudentClassNoRequest request) {
            return base.Channel.UpdateStudentClassNoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ZHXY.Application.PushService.UpdateStudentClassNoResponse> UpdateStudentClassNoAsync(string SiteID, string StuNo, string NewClassNo) {
            ZHXY.Application.PushService.UpdateStudentClassNoRequest inValue = new ZHXY.Application.PushService.UpdateStudentClassNoRequest();
            inValue.Body = new ZHXY.Application.PushService.UpdateStudentClassNoRequestBody();
            inValue.Body.SiteID = SiteID;
            inValue.Body.StuNo = StuNo;
            inValue.Body.NewClassNo = NewClassNo;
            return ((ZHXY.Application.PushService.数据中心接口服务Soap)(this)).UpdateStudentClassNoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ZHXY.Application.PushService.UpdateStudentStatusResponse ZHXY.Application.PushService.数据中心接口服务Soap.UpdateStudentStatus(ZHXY.Application.PushService.UpdateStudentStatusRequest request) {
            return base.Channel.UpdateStudentStatus(request);
        }
        
        public string UpdateStudentStatus(string SiteID, string StuNo, string Status) {
            ZHXY.Application.PushService.UpdateStudentStatusRequest inValue = new ZHXY.Application.PushService.UpdateStudentStatusRequest();
            inValue.Body = new ZHXY.Application.PushService.UpdateStudentStatusRequestBody();
            inValue.Body.SiteID = SiteID;
            inValue.Body.StuNo = StuNo;
            inValue.Body.Status = Status;
            ZHXY.Application.PushService.UpdateStudentStatusResponse retVal = ((ZHXY.Application.PushService.数据中心接口服务Soap)(this)).UpdateStudentStatus(inValue);
            return retVal.Body.UpdateStudentStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ZHXY.Application.PushService.UpdateStudentStatusResponse> ZHXY.Application.PushService.数据中心接口服务Soap.UpdateStudentStatusAsync(ZHXY.Application.PushService.UpdateStudentStatusRequest request) {
            return base.Channel.UpdateStudentStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<ZHXY.Application.PushService.UpdateStudentStatusResponse> UpdateStudentStatusAsync(string SiteID, string StuNo, string Status) {
            ZHXY.Application.PushService.UpdateStudentStatusRequest inValue = new ZHXY.Application.PushService.UpdateStudentStatusRequest();
            inValue.Body = new ZHXY.Application.PushService.UpdateStudentStatusRequestBody();
            inValue.Body.SiteID = SiteID;
            inValue.Body.StuNo = StuNo;
            inValue.Body.Status = Status;
            return ((ZHXY.Application.PushService.数据中心接口服务Soap)(this)).UpdateStudentStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ZHXY.Application.PushService.News_GetNewsListResponse ZHXY.Application.PushService.数据中心接口服务Soap.News_GetNewsList(ZHXY.Application.PushService.News_GetNewsListRequest request) {
            return base.Channel.News_GetNewsList(request);
        }
        
        public string News_GetNewsList(string ClassID, string PageSize, string PageIndex) {
            ZHXY.Application.PushService.News_GetNewsListRequest inValue = new ZHXY.Application.PushService.News_GetNewsListRequest();
            inValue.Body = new ZHXY.Application.PushService.News_GetNewsListRequestBody();
            inValue.Body.ClassID = ClassID;
            inValue.Body.PageSize = PageSize;
            inValue.Body.PageIndex = PageIndex;
            ZHXY.Application.PushService.News_GetNewsListResponse retVal = ((ZHXY.Application.PushService.数据中心接口服务Soap)(this)).News_GetNewsList(inValue);
            return retVal.Body.News_GetNewsListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ZHXY.Application.PushService.News_GetNewsListResponse> ZHXY.Application.PushService.数据中心接口服务Soap.News_GetNewsListAsync(ZHXY.Application.PushService.News_GetNewsListRequest request) {
            return base.Channel.News_GetNewsListAsync(request);
        }
        
        public System.Threading.Tasks.Task<ZHXY.Application.PushService.News_GetNewsListResponse> News_GetNewsListAsync(string ClassID, string PageSize, string PageIndex) {
            ZHXY.Application.PushService.News_GetNewsListRequest inValue = new ZHXY.Application.PushService.News_GetNewsListRequest();
            inValue.Body = new ZHXY.Application.PushService.News_GetNewsListRequestBody();
            inValue.Body.ClassID = ClassID;
            inValue.Body.PageSize = PageSize;
            inValue.Body.PageIndex = PageIndex;
            return ((ZHXY.Application.PushService.数据中心接口服务Soap)(this)).News_GetNewsListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ZHXY.Application.PushService.News_GetTopNewsListResponse ZHXY.Application.PushService.数据中心接口服务Soap.News_GetTopNewsList(ZHXY.Application.PushService.News_GetTopNewsListRequest request) {
            return base.Channel.News_GetTopNewsList(request);
        }
        
        public string News_GetTopNewsList(int TopNum) {
            ZHXY.Application.PushService.News_GetTopNewsListRequest inValue = new ZHXY.Application.PushService.News_GetTopNewsListRequest();
            inValue.Body = new ZHXY.Application.PushService.News_GetTopNewsListRequestBody();
            inValue.Body.TopNum = TopNum;
            ZHXY.Application.PushService.News_GetTopNewsListResponse retVal = ((ZHXY.Application.PushService.数据中心接口服务Soap)(this)).News_GetTopNewsList(inValue);
            return retVal.Body.News_GetTopNewsListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ZHXY.Application.PushService.News_GetTopNewsListResponse> ZHXY.Application.PushService.数据中心接口服务Soap.News_GetTopNewsListAsync(ZHXY.Application.PushService.News_GetTopNewsListRequest request) {
            return base.Channel.News_GetTopNewsListAsync(request);
        }
        
        public System.Threading.Tasks.Task<ZHXY.Application.PushService.News_GetTopNewsListResponse> News_GetTopNewsListAsync(int TopNum) {
            ZHXY.Application.PushService.News_GetTopNewsListRequest inValue = new ZHXY.Application.PushService.News_GetTopNewsListRequest();
            inValue.Body = new ZHXY.Application.PushService.News_GetTopNewsListRequestBody();
            inValue.Body.TopNum = TopNum;
            return ((ZHXY.Application.PushService.数据中心接口服务Soap)(this)).News_GetTopNewsListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ZHXY.Application.PushService.Portal_GetNoticeListResponse ZHXY.Application.PushService.数据中心接口服务Soap.Portal_GetNoticeList(ZHXY.Application.PushService.Portal_GetNoticeListRequest request) {
            return base.Channel.Portal_GetNoticeList(request);
        }
        
        public string Portal_GetNoticeList(string SiteID, string TypeID, string SearchType, string SearchText, int PageIndex, int PageSize) {
            ZHXY.Application.PushService.Portal_GetNoticeListRequest inValue = new ZHXY.Application.PushService.Portal_GetNoticeListRequest();
            inValue.Body = new ZHXY.Application.PushService.Portal_GetNoticeListRequestBody();
            inValue.Body.SiteID = SiteID;
            inValue.Body.TypeID = TypeID;
            inValue.Body.SearchType = SearchType;
            inValue.Body.SearchText = SearchText;
            inValue.Body.PageIndex = PageIndex;
            inValue.Body.PageSize = PageSize;
            ZHXY.Application.PushService.Portal_GetNoticeListResponse retVal = ((ZHXY.Application.PushService.数据中心接口服务Soap)(this)).Portal_GetNoticeList(inValue);
            return retVal.Body.Portal_GetNoticeListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ZHXY.Application.PushService.Portal_GetNoticeListResponse> ZHXY.Application.PushService.数据中心接口服务Soap.Portal_GetNoticeListAsync(ZHXY.Application.PushService.Portal_GetNoticeListRequest request) {
            return base.Channel.Portal_GetNoticeListAsync(request);
        }
        
        public System.Threading.Tasks.Task<ZHXY.Application.PushService.Portal_GetNoticeListResponse> Portal_GetNoticeListAsync(string SiteID, string TypeID, string SearchType, string SearchText, int PageIndex, int PageSize) {
            ZHXY.Application.PushService.Portal_GetNoticeListRequest inValue = new ZHXY.Application.PushService.Portal_GetNoticeListRequest();
            inValue.Body = new ZHXY.Application.PushService.Portal_GetNoticeListRequestBody();
            inValue.Body.SiteID = SiteID;
            inValue.Body.TypeID = TypeID;
            inValue.Body.SearchType = SearchType;
            inValue.Body.SearchText = SearchText;
            inValue.Body.PageIndex = PageIndex;
            inValue.Body.PageSize = PageSize;
            return ((ZHXY.Application.PushService.数据中心接口服务Soap)(this)).Portal_GetNoticeListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ZHXY.Application.PushService.Portal_GetNoticeContentResponse ZHXY.Application.PushService.数据中心接口服务Soap.Portal_GetNoticeContent(ZHXY.Application.PushService.Portal_GetNoticeContentRequest request) {
            return base.Channel.Portal_GetNoticeContent(request);
        }
        
        public object Portal_GetNoticeContent(string SiteID, string Guid) {
            ZHXY.Application.PushService.Portal_GetNoticeContentRequest inValue = new ZHXY.Application.PushService.Portal_GetNoticeContentRequest();
            inValue.Body = new ZHXY.Application.PushService.Portal_GetNoticeContentRequestBody();
            inValue.Body.SiteID = SiteID;
            inValue.Body.Guid = Guid;
            ZHXY.Application.PushService.Portal_GetNoticeContentResponse retVal = ((ZHXY.Application.PushService.数据中心接口服务Soap)(this)).Portal_GetNoticeContent(inValue);
            return retVal.Body.Portal_GetNoticeContentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ZHXY.Application.PushService.Portal_GetNoticeContentResponse> ZHXY.Application.PushService.数据中心接口服务Soap.Portal_GetNoticeContentAsync(ZHXY.Application.PushService.Portal_GetNoticeContentRequest request) {
            return base.Channel.Portal_GetNoticeContentAsync(request);
        }
        
        public System.Threading.Tasks.Task<ZHXY.Application.PushService.Portal_GetNoticeContentResponse> Portal_GetNoticeContentAsync(string SiteID, string Guid) {
            ZHXY.Application.PushService.Portal_GetNoticeContentRequest inValue = new ZHXY.Application.PushService.Portal_GetNoticeContentRequest();
            inValue.Body = new ZHXY.Application.PushService.Portal_GetNoticeContentRequestBody();
            inValue.Body.SiteID = SiteID;
            inValue.Body.Guid = Guid;
            return ((ZHXY.Application.PushService.数据中心接口服务Soap)(this)).Portal_GetNoticeContentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ZHXY.Application.PushService.Portal_SetNoticeReadStatusResponse ZHXY.Application.PushService.数据中心接口服务Soap.Portal_SetNoticeReadStatus(ZHXY.Application.PushService.Portal_SetNoticeReadStatusRequest request) {
            return base.Channel.Portal_SetNoticeReadStatus(request);
        }
        
        public string Portal_SetNoticeReadStatus(string SiteID, string Guid, string Name) {
            ZHXY.Application.PushService.Portal_SetNoticeReadStatusRequest inValue = new ZHXY.Application.PushService.Portal_SetNoticeReadStatusRequest();
            inValue.Body = new ZHXY.Application.PushService.Portal_SetNoticeReadStatusRequestBody();
            inValue.Body.SiteID = SiteID;
            inValue.Body.Guid = Guid;
            inValue.Body.Name = Name;
            ZHXY.Application.PushService.Portal_SetNoticeReadStatusResponse retVal = ((ZHXY.Application.PushService.数据中心接口服务Soap)(this)).Portal_SetNoticeReadStatus(inValue);
            return retVal.Body.Portal_SetNoticeReadStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ZHXY.Application.PushService.Portal_SetNoticeReadStatusResponse> ZHXY.Application.PushService.数据中心接口服务Soap.Portal_SetNoticeReadStatusAsync(ZHXY.Application.PushService.Portal_SetNoticeReadStatusRequest request) {
            return base.Channel.Portal_SetNoticeReadStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<ZHXY.Application.PushService.Portal_SetNoticeReadStatusResponse> Portal_SetNoticeReadStatusAsync(string SiteID, string Guid, string Name) {
            ZHXY.Application.PushService.Portal_SetNoticeReadStatusRequest inValue = new ZHXY.Application.PushService.Portal_SetNoticeReadStatusRequest();
            inValue.Body = new ZHXY.Application.PushService.Portal_SetNoticeReadStatusRequestBody();
            inValue.Body.SiteID = SiteID;
            inValue.Body.Guid = Guid;
            inValue.Body.Name = Name;
            return ((ZHXY.Application.PushService.数据中心接口服务Soap)(this)).Portal_SetNoticeReadStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ZHXY.Application.PushService.Portal_GetAffairListResponse ZHXY.Application.PushService.数据中心接口服务Soap.Portal_GetAffairList(ZHXY.Application.PushService.Portal_GetAffairListRequest request) {
            return base.Channel.Portal_GetAffairList(request);
        }
        
        public string Portal_GetAffairList(string SiteID, string UID) {
            ZHXY.Application.PushService.Portal_GetAffairListRequest inValue = new ZHXY.Application.PushService.Portal_GetAffairListRequest();
            inValue.Body = new ZHXY.Application.PushService.Portal_GetAffairListRequestBody();
            inValue.Body.SiteID = SiteID;
            inValue.Body.UID = UID;
            ZHXY.Application.PushService.Portal_GetAffairListResponse retVal = ((ZHXY.Application.PushService.数据中心接口服务Soap)(this)).Portal_GetAffairList(inValue);
            return retVal.Body.Portal_GetAffairListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ZHXY.Application.PushService.Portal_GetAffairListResponse> ZHXY.Application.PushService.数据中心接口服务Soap.Portal_GetAffairListAsync(ZHXY.Application.PushService.Portal_GetAffairListRequest request) {
            return base.Channel.Portal_GetAffairListAsync(request);
        }
        
        public System.Threading.Tasks.Task<ZHXY.Application.PushService.Portal_GetAffairListResponse> Portal_GetAffairListAsync(string SiteID, string UID) {
            ZHXY.Application.PushService.Portal_GetAffairListRequest inValue = new ZHXY.Application.PushService.Portal_GetAffairListRequest();
            inValue.Body = new ZHXY.Application.PushService.Portal_GetAffairListRequestBody();
            inValue.Body.SiteID = SiteID;
            inValue.Body.UID = UID;
            return ((ZHXY.Application.PushService.数据中心接口服务Soap)(this)).Portal_GetAffairListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ZHXY.Application.PushService.Portal_SendInstantMessageResponse ZHXY.Application.PushService.数据中心接口服务Soap.Portal_SendInstantMessage(ZHXY.Application.PushService.Portal_SendInstantMessageRequest request) {
            return base.Channel.Portal_SendInstantMessage(request);
        }
        
        public string Portal_SendInstantMessage(string SiteID, string UID, string MsgType, string MsgContent) {
            ZHXY.Application.PushService.Portal_SendInstantMessageRequest inValue = new ZHXY.Application.PushService.Portal_SendInstantMessageRequest();
            inValue.Body = new ZHXY.Application.PushService.Portal_SendInstantMessageRequestBody();
            inValue.Body.SiteID = SiteID;
            inValue.Body.UID = UID;
            inValue.Body.MsgType = MsgType;
            inValue.Body.MsgContent = MsgContent;
            ZHXY.Application.PushService.Portal_SendInstantMessageResponse retVal = ((ZHXY.Application.PushService.数据中心接口服务Soap)(this)).Portal_SendInstantMessage(inValue);
            return retVal.Body.Portal_SendInstantMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ZHXY.Application.PushService.Portal_SendInstantMessageResponse> ZHXY.Application.PushService.数据中心接口服务Soap.Portal_SendInstantMessageAsync(ZHXY.Application.PushService.Portal_SendInstantMessageRequest request) {
            return base.Channel.Portal_SendInstantMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<ZHXY.Application.PushService.Portal_SendInstantMessageResponse> Portal_SendInstantMessageAsync(string SiteID, string UID, string MsgType, string MsgContent) {
            ZHXY.Application.PushService.Portal_SendInstantMessageRequest inValue = new ZHXY.Application.PushService.Portal_SendInstantMessageRequest();
            inValue.Body = new ZHXY.Application.PushService.Portal_SendInstantMessageRequestBody();
            inValue.Body.SiteID = SiteID;
            inValue.Body.UID = UID;
            inValue.Body.MsgType = MsgType;
            inValue.Body.MsgContent = MsgContent;
            return ((ZHXY.Application.PushService.数据中心接口服务Soap)(this)).Portal_SendInstantMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ZHXY.Application.PushService.GetMiddleLeaderListResponse ZHXY.Application.PushService.数据中心接口服务Soap.GetMiddleLeaderList(ZHXY.Application.PushService.GetMiddleLeaderListRequest request) {
            return base.Channel.GetMiddleLeaderList(request);
        }
        
        public string GetMiddleLeaderList(string SiteID) {
            ZHXY.Application.PushService.GetMiddleLeaderListRequest inValue = new ZHXY.Application.PushService.GetMiddleLeaderListRequest();
            inValue.Body = new ZHXY.Application.PushService.GetMiddleLeaderListRequestBody();
            inValue.Body.SiteID = SiteID;
            ZHXY.Application.PushService.GetMiddleLeaderListResponse retVal = ((ZHXY.Application.PushService.数据中心接口服务Soap)(this)).GetMiddleLeaderList(inValue);
            return retVal.Body.GetMiddleLeaderListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ZHXY.Application.PushService.GetMiddleLeaderListResponse> ZHXY.Application.PushService.数据中心接口服务Soap.GetMiddleLeaderListAsync(ZHXY.Application.PushService.GetMiddleLeaderListRequest request) {
            return base.Channel.GetMiddleLeaderListAsync(request);
        }
        
        public System.Threading.Tasks.Task<ZHXY.Application.PushService.GetMiddleLeaderListResponse> GetMiddleLeaderListAsync(string SiteID) {
            ZHXY.Application.PushService.GetMiddleLeaderListRequest inValue = new ZHXY.Application.PushService.GetMiddleLeaderListRequest();
            inValue.Body = new ZHXY.Application.PushService.GetMiddleLeaderListRequestBody();
            inValue.Body.SiteID = SiteID;
            return ((ZHXY.Application.PushService.数据中心接口服务Soap)(this)).GetMiddleLeaderListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ZHXY.Application.PushService.Portal_GetNoticesResponse ZHXY.Application.PushService.数据中心接口服务Soap.Portal_GetNotices(ZHXY.Application.PushService.Portal_GetNoticesRequest request) {
            return base.Channel.Portal_GetNotices(request);
        }
        
        public string Portal_GetNotices(string SiteID, string UID) {
            ZHXY.Application.PushService.Portal_GetNoticesRequest inValue = new ZHXY.Application.PushService.Portal_GetNoticesRequest();
            inValue.Body = new ZHXY.Application.PushService.Portal_GetNoticesRequestBody();
            inValue.Body.SiteID = SiteID;
            inValue.Body.UID = UID;
            ZHXY.Application.PushService.Portal_GetNoticesResponse retVal = ((ZHXY.Application.PushService.数据中心接口服务Soap)(this)).Portal_GetNotices(inValue);
            return retVal.Body.Portal_GetNoticesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ZHXY.Application.PushService.Portal_GetNoticesResponse> ZHXY.Application.PushService.数据中心接口服务Soap.Portal_GetNoticesAsync(ZHXY.Application.PushService.Portal_GetNoticesRequest request) {
            return base.Channel.Portal_GetNoticesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ZHXY.Application.PushService.Portal_GetNoticesResponse> Portal_GetNoticesAsync(string SiteID, string UID) {
            ZHXY.Application.PushService.Portal_GetNoticesRequest inValue = new ZHXY.Application.PushService.Portal_GetNoticesRequest();
            inValue.Body = new ZHXY.Application.PushService.Portal_GetNoticesRequestBody();
            inValue.Body.SiteID = SiteID;
            inValue.Body.UID = UID;
            return ((ZHXY.Application.PushService.数据中心接口服务Soap)(this)).Portal_GetNoticesAsync(inValue);
        }
    }
}
